### ISSUE TITLE
Please make storage configurable

### ISSUE THREAD

**Issue by jschanz** [telcat/vagrant-proxmox#15]
Please make "storage" configurable:

```ruby
sata0: "raid:#{config.qemu_disk_size},format=qcow2",
```
not everyone has a storage called raid, so it would be helpful, if this could be set by config.
Otherwise you'll get an error on boot like

```
create failed - storage 'raid' does not exists
```

**Comment by grappendorf** [comment]
Fixed in version 0.0.8
